### ISSUE TITLE
predict_one NotImplementedError:  error when using VotingClassifier

### ISSUE THREAD

**Issue by Yasmen-Wahba** [online-ml/river#1119]
Can you please help me out with the following error! 
The learning (i.e., learn-one) went fine with no errors, then when I try to predict, I get a NotImplemented error on predict_one
```
occPAC = multiclass.OutputCodeClassifier(classifier=linear_model.PAClassifier(), code_size=20, seed=24)
occLR  = multiclass.OutputCodeClassifier(classifier=linear_model.LogisticRegression(), code_size=20, seed=24)

model =(TFIDF(lowercase=True,ngram_range=(1,1))|ensemble.VotingClassifier([
                                  occPAC,occLR], use_probabilities= True) 
)

for text,label in test_data:
#     print(label)
    y_pred_before = model.predict_one(text)

error: NotImplementedError: 
```

**Comment by VaysseRobin** [comment]
Hello!
The problem here is that you are using two `OutputCodeClassifier` (OCC) and feeding them to a `VotingClassifier` with the `use_probabilities` set to `True` so that the `VotingClassifier` tries to calculate the probabilities of the OCC. However, with the OCC, it is impossible (to my knowledge) to output a probability so you can't use it with `use_probabilities=True`. 
So you have 2 options:
- Set `use_probabilities=False` in the `VotingClassifier`.
- Use `OneVsRestClassifier` instead of `OutputCodeClassifier` because OneVsRest is able to produce probabilities.

I hope this helped you!

**Comment by Yasmen-Wahba** [comment]
Thank you VaysseRobin !! That worked!!
