### ISSUE TITLE
KSWIN Detector accepts string in update method

### ISSUE THREAD

**Issue by SteZamboni** [online-ml/river#1205]
## Versions

**river version**: 0.15.0
**Python version**: 3.9.15
**Operating system**: macOS Ventura 13.2.1

## Describe the bug

Even if in the documentation (https://riverml.xyz/0.15.0/api/drift/KSWIN/) in the section "Methods" on the update method the type of the parameter x is `numbers.Number`, it is possible to call the update method with a string as a parameter and everything goes fine without any exception or warning.

### Expected behaviour

```
>>> a = drift.ADWIN()
>>> a.update(1)
ADWIN (
  delta=0.002
  clock=32
  max_buckets=5
  min_window_length=5
  grace_period=10
)
>>> a.update("qwerty")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python3.9/site-packages/river/drift/adwin.py", line 127, in update
    self._drift_detected = self._helper.update(x)
  File "build/lib.macosx-10.9-x86_64-cpython-38/river/drift/adwin_c.pyx", line 72, in river.drift.adwin_c.AdaptiveWindowing.update
TypeError: must be real number, not str
```

 ### Actual Behaviour:

```
>>> k.update(1)
KSWIN (
  alpha=0.005
  window_size=100
  stat_size=30
  seed=None
  window=deque([1], maxlen=100)
)
>>> k.update("asd")
KSWIN (
  alpha=0.005
  window_size=100
  stat_size=30
  seed=None
  window=deque([1, 'asd'], maxlen=100)
)
```

## Steps/code to reproduce

```python
# Sample code to reproduce the problem
# Please do your best to provide a Minimal, Reproducible Example: https://stackoverflow.com/help/minimal-reproducible-example

from river import drift
KSWINdetector = drift.KSWIN()
KSWINdetector.update(1)
KSWINdetector.update('qwerty')
```

**Comment by MaxHalford** [comment]
Hey there. Thanks for the clear MWE :)

So `ADWIN` raises an exception because it's written in Cython, and thus does type checking.

Other than in its Cython modules, River doesn't do type checking. This is for performance reasons. We prefer to write good documentation (and I'm glad you found the type hint in the documentation). We don't want to add explicit type checking because it would hinder performance, would go against the way idiomatic Python should be written, and isn't really harmful.

It's true that it feels weird that this code works, but then again under the hood it's using `scipy.stats.ks_2samp` which, and I quote, takes as inputs "assumed to be drawn from a continuous distribution". SciPy does not raise an exception if strings are passed. I don't see a huge issue if we follow the same principle. Let me quote the [robustess principle](https://www.wikiwand.com/en/Robustness_principle) here:

> Be conservative in what you do, be liberal in what you accept from others.
