### ISSUE TITLE
Add flexibility to delay parameter in progressive_val_score function

### ISSUE THREAD

**Issue by sarim-zafar** [online-ml/river#1214]
Hi @MaxHalford,

First of all, I would like to express my appreciation for the great work done in river. I am thoroughly enjoying working with it.

I have a question regarding the delay parameter in the progressive_val_score function. Is there a possibility to make it more flexible? Let me explain my use case.

Suppose I have a machine learning problem where each sample may receive feedback on a flexible interval rather than a fixed one. In other words, some samples may receive feedback after a few seconds, while others may receive it after a few minutes or hours. Currently, with the progressive_val_score function's implementation, I am unable to do this. I have to write my own function in which I have to manually push the feedback into the queue, which is quite time-consuming and impractical.

Is there a way to add a feature that allows me to push a specific time to give feedback into the queue? This would greatly improve the flexibility and usability of the progressive_val_score function in my use case.

Thank you for your time and consideration.

**Comment by MaxHalford** [comment]
Hey there @sarim-zafar 👋

> First of all, I would like to express my appreciation for the great work done in river. I am thoroughly enjoying working with it.

Cheers, I appreciate it.

> Suppose I have a machine learning problem where each sample may receive feedback on a flexible interval rather than a fixed one. In other words, some samples may receive feedback after a few seconds, while others may receive it after a few minutes or hours. Currently, with the progressive_val_score function's implementation, I am unable to do this. I have to write my own function in which I have to manually push the feedback into the queue, which is quite time-consuming and impractical.

Actually, the `delay` can be a parameter which takes as input the sample. Under the good, `evaluate.progressive_val_score` calls `stream.simulate_qa`. The latter takes care of bookkeeping, so that the model processes samples in the correct order. In `stream.simulate_qa`'s [documentation](https://riverml.xyz/0.15.0/api/stream/simulate-qa/), there is an example using a function as the `delay`.

Here is an example of what you could do:

```py
import random
from river import datasets
from river import evaluate
from river import metrics
from river import linear_model
from river import preprocessing

model = (
    preprocessing.StandardScaler() |
    linear_model.LogisticRegression()
)

dataset = datasets.Phishing()
dataset_with_ts = (
    ({'ts': i, **x}, y)
    for i, (x, y) in enumerate(dataset)
)

steps = evaluate.iter_progressive_val_score(
    model=model,
    dataset=dataset_with_ts,
    metric=metrics.ROCAUC(),
    moment=lambda x: x['ts'],
    delay=lambda x, y: random.randint(1, 5),
    step=200
)

for step in steps:
    print(step)
```

You'll get random results, because the `delay` is random. As you can see, the `moment` and `delay` can be configured based on the samples.

Note you could `pop` attributes from `x` if you don't want them to be passed to the model:

```py
moment=lambda x: x.pop('ts')
delay=lambda x, y: x.pop('delay')
```

Let me know if this doesn't fully answer your use-case!

**Comment by sarim-zafar** [comment]
Yes this is perfect. Thank you so much for the detailed and helpful reply.
