### ISSUE TITLE
ExtremelyFastDecisionTreeClassifier slower than HoeffdingTreeClassifier

### ISSUE THREAD

**Issue by clime** [online-ml/river#1221]
Hello, this is rather a question. I have tried to build an adaptive random forest (ensemble) out of ExtremelyFastDecisionTreeClassifier (by tweaking the one made for HoeffdingTreeClassifier).

The problem is that using ExtremelyFastDecisionTreeClassifier as the base tree slowed the ensemble training down by maybe a factor of 10x (or more). Is that expected? I thought ExtremelyFastDecisionTreeClassifier is going to be much faster than the Hoeffding one.

I can also see at https://riverml.xyz/0.13.0/benchmarks/ that ExtremelyFastDecisionTree is much slower than HoeffdingTree on the phishing dataset so maybe I should expect the HoeffdingTree to perform better despite the names?

**Comment by smastelini** [comment]
Hi @clime. Yes, that is expected. 

The extreme fast in the name only concerns convergence. Theoretically, EFDT converges faster to the structure a batch decision tree would generate by processing the whole data stream. That when compared with the vanilla HT. 

But in actual running time, HTs are much faster due to their simplicity.

**Comment by clime** [comment]
Thank you. That's a great answer. I was thinking the name might actually only refer to the speed of convergence but wasn't sure.
