### ISSUE TITLE
Guarantees for imbalanced `RandomSampler`

### ISSUE THREAD

**Issue by amogkam** [online-ml/river#1314]
What are the guarantees for `RandomSampler` with regards to number of sampled data points and how close the actual distributions will be to the desired distributions? Any corresponding proofs for this?

cc @MaxHalford

**Comment by MaxHalford** [comment]
Hey there. I'm not sure about proofs, because the formulas are quite basic. Take a look [here](https://maxhalford.github.io/blog/undersampling-ratios/) and [here](https://github.com/MaxHalford/pytorch-resample) for more information.

It's guaranteed that the amount of sampled points converges to the specified `sampling_rate`. I'm also guessing that the distribution will eventually converge to the `desired_dist`, but I have no theoretical guarantees to provide. There are probably proofs out there that make assumptions on your data. In practice, I assume this will depend on the nature of the data, so the best is to test this out yourself.
