### ISSUE TITLE
Use ASV 

### ISSUE THREAD

**Issue by MaxHalford** [online-ml/river#198]
It would great if we could set up [ASV](https://github.com/airspeed-velocity/asv) for monitoring the speed of our implementations.

**Comment by MaxHalford** [comment]
I'm getting comfortable with ASV. However, from reading [this](https://github.com/astropy/astropy/issues/6149) thread, it seems that setting up ASV via CI (i.e. Travis) isn't reliable. Instead we would need someone to volunteer a server to run AVS in a reliable manner.

In the meantime, I'm going to set things up so that ASV can be used locally to compare local work against master.

**Comment by MaxHalford** [comment]
For posterity, this is the Travis job I had in mind:

```sh
- stage: asv
    install:
      - python setup.py install
      - pip install asv
    script:
      - COMMIT_HASH=$(git rev-parse HEAD)
      - git config --global push.default matching
      - git clone https://${GH_TOKEN}@github.com/creme-ml/creme-benchmarks creme-benchmarks
      - cp benchmarks/.asv/results/benchmarks.json creme-benchmarks/benchmarks.json
      - cp benchmarks/.asv/results/travis/*.json --parents creme-benchmarks/travis
      - git add -A
      - git commit --allow-empty -m "Travis build $TRAVIS_BUILD_NUMBER; git commit $COMMIT_HASH"
      - git push --set-upstream origin master
    if: branch = "master"
```

**Comment by MaxHalford** [comment]
I've just added the `make bench` command. This will run the benchmarks for your latest local commit. It will also run the benchmarks against the master branch. It will then invoke the `asv compare` command to compare both versions of the code.

**Comment by remiadon** [comment]
Hi, don't know if that helps, but I'm also using ASV for a project. Performance-related benchmarks, as those prefixed by `time_` and `mem_` cannot be launched in a CI environment, because there is no guarantee on physical resources provided to your benchmarks. 

However I found that ASV is still relevant when it comes to tracking a specific metric for a given model/dataset, [as methods prefixed by `track_`](https://asv.readthedocs.io/en/stable/writing_benchmarks.html#tracking-generic)

An example [here](https://github.com/scikit-learn/scikit-learn/blob/5403e9fdaee6d4982c887ce2ae9a62ccd3955fbb/asv_benchmarks/benchmarks/common.py#L168)

**Comment by MaxHalford** [comment]
We've revamped the benchmarking process (currently in a pull request). There's no more the need for ASV.
