### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by SikandAlex** [online-ml/river#389]
I can't access any of the documentation? I get a 404 on river.xyz and the documentation link in ReadMe which is limiting me from using this library for an online ML recommendation system.

**Comment by SikandAlex** [comment]
I'm happy to help on this library but I'll need to understand the code better and even a minimal documentation would help me. I'd like to use river in the context of recommendation systems.

**Comment by MaxHalford** [comment]
Hey, sorry for the disturbance. The [development documentation](https://riverml.xyz/dev/) is available. We were going to wait for the PyPI package to be released, but I don't see any reason not to build the docs for version `0.1` in the meantime. The docs are building as we speak, and should be available soon.

**Comment by siniysv** [comment]
@MaxHalford Hey, just want to let you know that the link you posted is 404. No pressure, most likely you are working on it already. I would really like to explore this project, thank you!

**Comment by SikandAlex** [comment]
@MaxHalford yeah the link is 404 but let us know when it's up so I can explore further and work with this library. I'm an MS Candidate in Artificial Intelligence at Boston University looking to build an online learning recommendation system with data received as a stream S opposed to batch updates. Really interested in the field of online machine learning and once I get a look at the docs happy to help you flesh out this project more.

**Comment by MaxHalford** [comment]
It should be now... Basically the docs are available by default at [https://online-ml.github.io/river](https://online-ml.github.io/river). But because we're cool we've added a custom URL which is [https://riverml.xyz](https://riverml.xyz) (which is currently working, I just checked). Sometimes, when I push a new version of the docs, the custom URL gets dropped. I can't figure this out (maybe a wrong DNS setting @jacobmontiel).

Anyway, thanks for your interest! Our recommendation referent is @gbolmier who also did an internship at scikit-learn in New-York and knows @NicolasHug, who is the creator of [Surprise](http://surpriselib.com/). We'd love to be push online  recommendation forward as it seems there is an interest from the community. Note that Geoffrey wrote a series of notebooks which you can find in the [notebook examples](https://github.com/online-ml/river/tree/master/docs/examples) directory. The latter are also available on the documentation website. Enjoy!

**Comment by jacobmontiel** [comment]
The "development" documentation has changed its location to [https://riverml.xyz/latest/](https://riverml.xyz/latest/) and now the user is redirected to it by default.

> Sometimes, when I push a new version of the docs, the custom URL gets dropped. I can't figure this out (maybe a wrong DNS setting)

Regarding the site configuration, everything seems to be working fine. What I noticed though is that the `CNAME` file was deleted during the deployment of the documentation into the `gh-pages` branch breaking the map between the domain and the documentation.

**Comment by MaxHalford** [comment]
Where's the `CNAME` file? Is it something we have to version?

**Comment by jacobmontiel** [comment]
It is in the gh-pages branch: https://github.com/online-ml/river/blob/gh-pages/CNAME

Found this [here](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages#cname-errors):
> For your site to render at the correct domain, make sure your CNAME file still exists in the repository. For example, many static site generators force push to your repository, which can overwrite the CNAME file that was added to your repository when you configured your custom domain. If you build your site locally and push generated files to GitHub, make sure to pull the commit that added the CNAME file to your local repository first, so the file will be included in the build.

**Comment by MaxHalford** [comment]
Ok I added the `CNAME` file to the docs directory, it should do the trick :)

**Comment by chartpath** [comment]
Still can't access them on the custom domain (or the links at the bottom of Getting Started are broken).

**Comment by MaxHalford** [comment]
The website [is live](https://riverml.xyz/latest/), but indeed some links are broken. I'll fix them :)

**Comment by chartpath** [comment]
@MaxHalford thanks!

For any other disparate folks I just ran a static build at least to see the markdown files, can access here in the meantime: https://github.com/chartpath/river/tree/master/docs
