### ISSUE TITLE
Linear models non-idempotent when shuffling features

### ISSUE THREAD

**Issue by MaxHalford** [online-ml/river#410]
I just found out a silly issue that happens when a linear model used the `Random` initializer. The model's outputs will be sensitive to the feature order because of the way the initializer is called. Indeed, the order depends on the order of the `dict`, and isn't deterministic (like alphanumeric order).

@brcharron could you look into this? Here's the code to reproduce:

```py
import copy
import random
from river import datasets
from river import linear_model
from river import optim
from river import preprocessing

def check_shuffle_features_no_impact(model, dataset):

    from river import utils

    shuffled = copy.deepcopy(model)

    for i, (x, y) in enumerate(dataset):

        # Shuffle the features
        features = list(x.keys())
        random.shuffle(features)
        x_shuffled = {i: x[i] for i in features}

        assert x == x_shuffled  # order doesn't matter for dicts

        if utils.inspect.isclassifier(model):
            y_pred = model.predict_proba_one(x)
            y_pred_shuffled = shuffled.predict_proba_one(x_shuffled)
        else:
            y_pred = model.predict_one(x)
            y_pred_shuffled = shuffled.predict_one(x_shuffled)
        
        print(i)
        print(y_pred)
        print(model['LogisticRegression']._weights)
        print(y_pred_shuffled)
        print(shuffled['LogisticRegression']._weights)
        print()

        if utils.inspect.ismoregressor(model):
            for o in y_pred:
                assert math.isclose(y_pred[o], y_pred_shuffled[o])
        elif utils.inspect.isregressor(model):
            assert math.isclose(y_pred, y_pred_shuffled)
        else:
            assert y_pred == y_pred_shuffled

        model.learn_one(x, y)
        shuffled.learn_one(x_shuffled, y)

model = (
    preprocessing.StandardScaler() |
    linear_model.LogisticRegression(
        initializer=optim.initializers.Normal(seed=42),
    )
)

dataset = datasets.Phishing()
check_shuffle_features_no_impact(model, dataset)
```

**Comment by brcharron** [comment]
@MaxHalford Thank you for the complete example. What do you think should be the expected behavior?
Sorting keys (features) before any operation that can induce initialization is possible but it may add significant overhead and to my understanding, any object can be a key, there may not be a total order.

**Comment by MaxHalford** [comment]
Thanks for challenging me on this. There's no correct answer, or so it seems to me right now. In an ideal world, we want every model to be idempotent with respect the order of the features in the `dict`.

Maybe that we can do something like sorting the features lexigraphically only when there is at least 2 new features that need weight initialization (such as during the first call to `learn_one`).

**Comment by brcharron** [comment]
That's a good point, I was wondering how to change `VectorDict` but your requirement is at the model level so it can be taken care of by the model. It's not only at the first call of `learn_one` I think, a second call may include features not seen in the first call. So maybe first check whether there are new features and if so reorder the input `x` then apply `learn_one` as usual. If the reorder fails because keys are not comparable then just skip the reordering. An advantage is that there is no overhead in `VectorDict` operations. A disadvantage is that it must be done for every model.

**Comment by MaxHalford** [comment]
Thanks for being a soundboard, it helps a lot. I'll think about it a bit more. Maybe that it's something that needs to be handled in the initializer.

**Comment by MaxHalford** [comment]
Ok so I've given it some thought and I think it's fine the way it is. We don't want to introduce more complexity. At least we now have a written trace of this edge-case :)
