### ISSUE TITLE
Incremental Learning for DL architectures, BERT based models

### ISSUE THREAD

**Issue by katreparitosh** [online-ml/river#431]
Hello,

First of all, fantastic work with River! 

I wanted to ask whether River would support Keras/PyTorch/Tensorflow, etc. for incremental learning on BERT-based models or DL architectures.

It would be great if you could elaborate on what would it take to implement this functionality for the above models. Also, how different would it be to implement it for non-linear models?

Kudos, amazing work!

**Comment by MaxHalford** [comment]
Hey there. 

There's a `PyTorch2RiverRegressor` class in the `compat` module. As a general thought, deep learning models are incremental in nature because they learn from mini-batches and don't require the whole dataset in memory. I'm not sure there's a lot for us to bring in this area.

Thanks for the kind words and the interest.

**Comment by katreparitosh** [comment]
Hey

Thanks a lot for the information. 

I will look into it and let you know if I have any issues.
