### ISSUE TITLE
streamz as input

### ISSUE THREAD

**Issue by remiadon** [online-ml/river#470]
Hi, awesome project, as always

This issue actually mirrors one from scikit-multiflow, [here](https://github.com/scikit-multiflow/scikit-multiflow/issues/106)

[Streamz](https://streamz.readthedocs.io/en/latest/index.html) is a pythonic library to handle data streams. I think using it as a base ingestion / data structure provider library would benefit this project. After all, does'nt scikit-learn use numpy as a base component ?

**Comment by MaxHalford** [comment]
Hey Rémi!

I believe I'm aligned with is said in the issue thread you mention: model fitting should be decoupled from data access. If we're aligned on this point, then I'm not really sure what there is to do. Currently you can use Streamz to stream in dicts that you feed to a River model. Is there any particular pain point that makes this difficult? If so, what do you propose? I don't think it's a good idea to couple both libraries. If using both libraries together is difficult, then maybe we can add a utility method to the `stream` module. For instance, is it easy to take a Streamz DataFrame and yield dicts from it?

> After all, does'nt scikit-learn use numpy as a base component ?

We use dicts as the fundamental data type we work with. I don't see Streamz as an alternative to dicts. For me it's just a tool that can be used to produce dicts.

Meta: I think these kind of discussions can and should be done in the [Discussions tab](https://github.com/online-ml/river/discussions) rather than in an issue.

**Comment by remiadon** [comment]
Hi Max,

> model fitting should be decoupled from data access

We are aligned on this point :)

> I don't think it's a good idea to couple both libraries

I just thought it was a good (not so drop-in, I admit) replacement for your `stream` module.

> We use dicts as the fundamental data type we work with

Yes and I believe it's a really good design choice. 

------- 

I guess what I can propose is more an example of coupling streamz with river, which would benefit both tools !

Meta: I was not aware of github's Dicussion Tab. Apologies

**Comment by MaxHalford** [comment]
Yes I guess a good move forward would simply be to add an example in `docs/examples` :)

**Comment by remiadon** [comment]
Closing this, I'll instantiate a PR if needed
