### ISSUE TITLE
Supplying confusion matrix to metrics can be confusing 

### ISSUE THREAD

**Issue by tachyonicClock** [online-ml/river#541]
## Versions

**river version**: Latest commit 037ffc6
**Python version**: 3.8.5
**Operating system**: Linux

## Describe the bug

When a confusion matrix is supplied to Recall/Precision to store internal state it can create weird unexpected behaviours. Such as double counting and stopping metrics from rolling as expected. I imagine this problem is made worse when the `Metrics` container class is used especially if multiple metrics reference the confusion matrix.

## Steps/code to reproduce

**Double updating metrics**
When both the confusion matrix and the recall matrix are updated the updates are counted twice by both objects

```python
cm = metrics.ConfusionMatrix()
recall = metrics.Recall(pos_val=1, cm=cm)

for true_y, pred_y in zip([1,1,0,1], [1,0,0,1]):
    recall.update(true_y, pred_y)
    cm.update(true_y, pred_y)
    print(cm)
```

```

        True
  True     2
         False   True
  False      0      0
   True      2      2
         False   True
  False      2      0
   True      2      2
         False   True
  False      2      0
   True      2      4
```

**Rolling metrics that don't roll**

```python
cm = metrics.ConfusionMatrix()
recall = metrics.Rolling(metrics.Recall(pos_val=1, cm=cm), window_size=1)

for true_y, pred_y in zip([1,1,0,1], [1,0,0,1]):
    cm.update(true_y, pred_y)
    print(recall)
```

```

Recall: 1.	(rolling 1)
Recall: 0.333333	(rolling 1)
Recall: 0.5	(rolling 1)
Recall: 0.75	(rolling 1)
```

## Possible Solutions
1. Remove the ability to use confusion matrices inside derived metrics.
2. Raise an error on update if a confusion matrix was provided and update the documentation.
3. Remove metrics derived from a confusion matrix. Replace them with methods on the confusion matrix itself. e.g `cm.get_recall(pos_val=1)`

I think 2 or 3 are the best idea but maybe there is a better option

**Comment by MaxHalford** [comment]
Hey there. Thanks for raising these API "issues". We've tried to make the `metrics` module flexible. I would consider the examples you've as bad examples. If you want to compute multiple metrics, you should be doing:

```py
from river.metrics import Precision, Recall

metrics = Recall() + Precision()

for true_y, pred_y in zip([1,1,0,1], [1,0,0,1]):
    metrics.update(true_y, pred_y)
```

The issue at the moment is that the `+` operator doesn't work with `ConfusionMetric`, but we could fix that. But you can still access the `cm` attribute of `Recall` or `Precision`.

```py
print(metrics[0].cm)
```

The advantage of being able to pass a confusion to a derived metric is that lowers the computational cost. For instance we can do:

```py
from river.metrics import Precision, Recall, ConfusionMatrix

cm = ConfusionMatrix()
metrics = Recall(cm) + Precision(cm)

for true_y, pred_y in zip([1,1,0,1], [1,0,0,1]):
    cm.update(true_y, pred_y)
```

The 3rd solution you propose provides the same benefits, but I rather have user-facing classes instead of methods attached to `ConfusionMatrix` that will be buried in the docs.
