### ISSUE TITLE
As a user I would like to create a customized datasets

### ISSUE THREAD

**Issue by rubcol** [online-ml/river#857]
There are many examples on datasets that are used in the examples. But I couldn't find any information documentation to create your own custom dataset. ?!

**Comment by MaxHalford** [comment]
That's a good remark! There's different aspects to consider.

At their very core, River datasets are just iterators. So you can use any function that yields:

```py
def custom_dataset():
    while True:
        yield {'foo': 'bar'}, 'baz'
        
for x, y in custom_dataset():
    print(x, y)
    break
```

For instance, you can pass such a function to `progressive_val_score`.

In truth, River datasets are not just iterators. They're classes that implement the `__iter__` method (which is why you can loop over them). They inherit from `river.datasets.base.Dataset` and contain some metadata. You can create a dataset like this as so:

```py
from river.datasets.base import Dataset, MULTI_CLF

class CustomDataset(Dataset):
    
    def __init__(self):
        super().__init__(
            task=MULTI_CLF,
            n_features=1
        )
    
    def __iter__(self):
        while True:
            yield {'foo': 'bar'}, 'baz'
            
for x, y in CustomDataset().take(10):
    print(x, y)
```

This may seem a bit ugly (at least I do). That's because I've never really intended for users to write their own datasets this way. I find that having users implement their datasets as pure iterators (the first example I gave) is sufficient. I may be wrong though!

For more details, I would suggest exploring the `datasets` directory in the codebase. It's rather straightforward. For instance, you'll find in there a `FileDataset` which is quite handy, as it avoids a lot of boilerplate. That class is currently private, but now that I'm writing this I can see the value of making it public in some other shape or form.

I hope this helps! I'm aligned that this should be documented somewhere. I just can't seem to find the time or motivation to work on documenting River right now.
