### ISSUE TITLE
Can't skip the unused column

### ISSUE THREAD

**Issue by occoder** [online-ml/river#866]
Hello, River experts
I mannually crafted a very simple abcde.csv dataset and try to use the example code to run through it.
The csv content looks like
```
foo,a,b,c,d,e
10,21.1,22.1,23.1,10.1,10000
50,21.2,22.2,23.2,5.8,20000
100,22.3,23.3,24.3,12.5,300000
```
The code snippet is as follows
```py
import pathlib
from river import stream
from river.datasets import base


class Abcde(base.FileDataset):
    """
    Formed from manually crafted csv file
    """

    def __init__(self):
        super().__init__(
            filename="abcde.csv", n_samples=3, n_features=4, task=base.REG
        )

    def __iter__(self):
        return stream.iter_csv(
            self.path,
            target="e",
            converters={"a": float, "b": float, "c": float, "d": float, "e": int},
        )
    @property
    def path(self):
        return pathlib.Path(__file__).parent.joinpath(self.filename)

from river import compose
from river import linear_model
from river import metrics
from river import preprocessing

dataset = Abcde()
model = compose.Pipeline(
    preprocessing.StandardScaler(),
    linear_model.LinearRegression()
 )

metric = metrics.Accuracy()

for x, y in dataset:
    y_pred = model.predict_one(x)      # make a prediction
    print(y_pred)
    metric = metric.update(y, y_pred)  # update the metric
    print(metric)
    model = model.learn_one(x, y)      # make the model learn
```
Unfortunetly, it gave following error prompt
```
TypeError: unsupported operand type(s) for -: 'str' and 'float'
```
After tracking down the root cause, it is the first column, i.e. foo, that is not taken into account as a feature and not converted either that casued such error and River didn't skip this unused column in the dataset.
I think it will be more reasonable to have River made to skip the unused column automatically considering enough information has already been provided. Or can I explicitly specify the feature columns instead of only total feature numbers?
Thanks for any comments.

**Comment by gbolmier** [comment]
Hello @occoder, the second line of your csv has 7 values whereas all the others have 6. Have you also tried adding `foo` to the `converters` param dict of `stream.iter_csv`?

**Comment by occoder** [comment]
> Hello @occoder, the second line of your csv has 7 values whereas all the others have 6. Have you also tried adding `foo` to the `converters` param dict of `stream.iter_csv`?
Sorry, my bad to paste in wrong data. I've fixed it. But it won't affect the problem.
If I put "foo" into converters dict, the error will be gone. But it just hides the problem that River actually takes "foo" as a feature.

**Comment by smastelini** [comment]
Hi @occoder, you can also pass foo to `drop` in `iter_csv`.

**Comment by gbolmier** [comment]
`stream.iter_csv` is using [`csv.DictReader`](https://docs.python.org/3/library/csv.html#csv.DictReader) internally (from the standard lib). From the `csv` module [documentation](https://docs.python.org/3/library/csv.html#:~:text=Each%20row%20read%20from%20the%20csv%20file%20is%20returned%20as%20a%20list%20of%20strings.%20No%20automatic%20data%20type%20conversion%20is%20performed):

> Each row read from the csv file is returned as a list of strings. No automatic data type conversion is performed

I guess that's why @MaxHalford added the `converters` argument to `stream.iter_csv`, this is indicated in the function's documentation in the returns section:

https://github.com/online-ml/river/blob/68aa41c32543a77f5aa53895c0c894e63f9ca712/river/stream/iter_csv.py#L83-L85

Unfortunately the returns section is not displayed in the [riverml.xyz documentation](https://riverml.xyz/latest/api/stream/iter-csv/). I think a mention in the `converters` argument documentation would make it clearer too:

https://github.com/online-ml/river/blob/68aa41c32543a77f5aa53895c0c894e63f9ca712/river/stream/iter_csv.py#L61-L62

**Comment by MaxHalford** [comment]
> Unfortunately the returns section is not displayed in the [riverml.xyz documentation](https://riverml.xyz/latest/api/stream/iter-csv/).

Nice catch!
